In [1]:
from dataprep import dataprep
from modeltrain import modeltrain
from hmm_test import hmm_test

import numpy as np

# Cross validation implementation

In [ ]:
itr = 5  # number of cross-validation iterations

# Cross validation implementation
cv_train_acc = []
cv_acc = []
hmm_list = []
train_list = []
test_list = []

for i in range(itr):
    
    train_data, test_data, labels = dataprep("database_inc_sampchar", shuffle=True, max_labels=0, max_samples=0, nr_test=5)

    hmm_learn, train_acc = modeltrain(train_data, labels, 20)

    acc, res_labl_list = hmm_test(hmm_learn, test_data, labels )
    
    cv_train_acc += [train_acc]
    cv_acc += [acc]
    hmm_list += [hmm_learn]
    train_list += [train_data]
    test_list += [test_data]

mean_acc = np.mean(np.array(cv_acc))
print(mean_acc)


Database read is  database_inc_sampchar
Labels used are  ['A', 'C', 'K', 'P', 'X', 'T', '+', 'N', 'V', '4']
Total training samples are  15  and testing samples are  5 


 ------------ CHARACTER  A ------------
Estimated q:
[1. 0.]

Estimated A:
[[9.56647399e-001 4.33526012e-002]
 [1.36939112e-110 1.00000000e+000]]

Estimated means:
[[ 10.07453272   0.2695875 ]
 [ 38.23301466 -10.26848084]]

Estimated covariances:
[[[2.57933411e+00 1.76222658e+01]
  [1.76222658e+01 4.34708546e+03]]

 [[2.11495653e+01 1.61311711e+01]
  [1.61311711e+01 2.60117094e+02]]]
Avg probability over test samples is 0.016303229541661156

 ------------ CHARACTER  C ------------
Estimated q:
[6.73100558e-29 1.18422681e-01 8.81577319e-01]

Estimated A:
[[0.81966627 0.02845416 0.15187957]
 [0.00893078 0.25234095 0.73872826]
 [0.08327346 0.05041174 0.8663148 ]]

Estimated means:
[[  9.65842173  68.58303718]
 [  8.56948873  -5.78082227]
 [  9.80211941 -12.80421197]]

Estimated covariances:
[[[1.13288049e+00 1.03990195e+

In [ ]:
print(cv_acc)
print(cv_train_acc)

In [ ]:


print("---------------- RESULTS: ---------------- ")
for k in range(len(labels)):
    print("\n Character: ", labels[k])
    print("Test accuracy: ",acc[k], "and resulting labels: ",res_labl_list[k])
    print("Training accuracy: (log)", train_acc[k])
    